spring.application.name=springboot-TMS

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/springboot-tms
spring.datasource.username=iamsunilrawat
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.servlet.context-path=/api/v1
spring.h2.console.enabled=true
